# Generated by Django 2.0.7 on 2018-07-29 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicStrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComicStripFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('sequence', models.IntegerField()),
                ('move', models.IntegerField(blank=True, null=True)),
                ('comic_strip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic_strip.ComicStrip')),
            ],
        ),
    ]
