# Generated by Django 2.0.7 on 2018-07-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_strip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicstrip',
            name='description',
            field=models.TextField(default='Lorem ipsum'),
            preserve_default=False,
        ),
    ]
