# Generated by Django 2.0.7 on 2018-08-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20180801_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='Solution / Proposed solution'),
        ),
    ]
