# Generated by Django 2.0.7 on 2018-08-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketupvoter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='feature_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
